parse_config:
  assign_combos_to_layers: false
  preprocess: true
  mark_alternate_layer_activators: true
  skip_binding_parsing: false
  zmk_keycode_map:
    AMPERSAND: '&'
    AMPS: '&'
    APOS: .
    APOSTROPHE: <
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: '\'
    BSLH: \
    BSPC: ✂️
    CARET: ^
    COLON: ':'
    COMMA: ','
    DEL: 🗑️
    DLLR: $
    DOLLAR: $
    DOT: '.'
    DOUBLE_QUOTES: '"'
    DQT: '"'
    END: 🏁
    EQUAL: '='
    ESC: ☢️
    ESCAPE: ☢️
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    HOME: 🏡
    INS: 📥
    INSERT: 📥
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LCTRL: 🕹️
    LALT: ☯︎
    LGUI: 🐧
    LSHFT: ⏏
    LSHIFT: ⏏
    LEFT_CONTROL: 🕹️
    LEFT_ALT: ☯︎
    LEFT_GUI: 🐧
    LEFT_SHFT: ⏏
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PG_DN: 📜🢃
    PG_UP: 📜🢁
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    PSCRN: 📸
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RET: ╰┈➤
    RETURN: ╰┈➤
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ';'
    SEMICOLON:  ';'
    SINGLE_QUOTE: ''''
    SLASH: '/'
    SPACE: "🪐"
    SQT: ''''
    STAR: '*'
    TAB: 🔮
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
    RCTRL: 🕹️
    RALT:  ☯︎
    RGUI: 🐧
    RSHFT: ⏏
    RSHIFT: ⏏
    RIGHT_CONTROL: 🕹️
    RIGHT_ALT: ☯︎
    RIGHT_GUI: 🐧
    RIGHT_SHFT: ⏏
    LEFT: 🡄
    RIGHT: 🡆
    UP: 🡅
    DOWN: 🡇
    C_REWIND: '⏮'
    C_FAST_FORWARD: '⏭'
    C_PAUSE: '⏯'
    C_MUTE: "VOL\nMUTE"
    C_VOLUME_DOWN: "VOL\nDOWN"
    C_VOLUME_UP: "VOL\nUP"
    C_BRIGHTNESS_DEC: '☀↓'
    C_BRIGHTNESS_INC: '☀↑'
    LA(LEFT): ↞
    LA(RIGHT): ↠
    LG(LEFT): ⇤
    LG(RIGHT): ⇥
    'LS(LC(LG(LALT)))': 'HYPER'
    'RS(RC(RG(RALT)))': 'HYPER'
    'LC(LG(LALT))': 'MEH'
    'RC(RG(RALT))': 'MEH'
    'LG(Q)': '⌘Q'
    'LG(W)': '⌘W'
    'LG(GRAVE)': '⌘`'
    'LG(Z)': '⌘Z'
    'LG(X)': '⌘X'
    'LG(C)': '⌘C'
    'LG(V)': '⌘V'
    'LC(TAB)': '⌃↹'
    'LS(LC(TAB))': '⌃⇧↹'
  raw_binding_map:
    '&none': ''
    '&trans': ''
    '&to L_DEF': ''

    # ctrl-tabdance
    '&tdc_dot':
      tap: "💃."
    '&tdc_com':
      tap: "💃,"
    '&tdc_excl':
      tap: "💃Q"
    '&tdc_ques':
      tap: "💃/"


    # Mouse emo
    '&msc SCRL_LEFT':
      tap: 🖱️🢀
    '&msc SCRL_RIGHT':
      tap: 🖱️🢂
    '&msc SCRL_DOWN':
      tap: 🖱️🢃
    '&msc SCRL_UP':
      tap: 🖱️🢁

    '&mkp LCLK':
      tap: 🖱️L
    '&mkp MCLK':
      tap: 🖱️M
    '&mkp RCLK':
      tap: 🖱️R

    '&mmv MOVE_LEFT':
      tap: 🖱️🡄
    '&mmv MOVE_RIGHT':
      tap: 🖱️🡆
    '&mmv MOVE_UP':
      tap: 🖱️🡅
    '&mmv MOVE_DOWN':
      tap: 🖱️🡇

    # LED macros
    '&led_red 3': 'NAV'
    '&led_blu 2': 'SIGNS'
    '&led_pur 1': 'NUM'
    '&htl_nav 5': 'NAV'
    '&htl_mg 2': '⌐╦╦═─💥'
    '&htl_sn 1': '🔢'

    # toggle default layer
    '&tok_def A': {s: 🏠︎, t: A}
    '&tok_def B': {s: 🏠︎, t: B}
    '&tok_def C': {s: 🏠︎, t: C}
    '&tok_def D': {s: 🏠︎, t: D}
    '&tok_def E': {s: 🏠︎, t: E}

    '&tok_def F': {s: 🏠︎, t: F}
    '&tok_def G': {s: 🏠︎, t: G}
    '&tok_def H': {s: 🏠︎, t: H}
    '&tok_def I': {s: 🏠︎, t: I}
    '&tok_def J': {s: 🏠︎, t: J}

    '&tok_def K': {s: 🏠︎, t: K}
    '&tok_def L': {s: 🏠︎, t: L}
    '&tok_def M': {s: 🏠︎, t: M}
    '&tok_def N': {s: 🏠︎, t: N}
    '&tok_def O': {s: 🏠︎, t: O}

    '&tok_def P': {s: 🏠︎, t: P}
    '&tok_def Q': {s: 🏠︎, t: Q}
    '&tok_def R': {s: 🏠︎, t: R}
    '&tok_def S': {s: 🏠︎, t: S}
    '&tok_def T': {s: 🏠︎, t: T}

    '&tok_def U': {s: 🏠︎, t: U}
    '&tok_def V': {s: 🏠︎, t: V}
    '&tok_def W': {s: 🏠︎, t: W}
    '&tok_def X': {s: 🏠︎, t: X}
    '&tok_def Y': {s: 🏠︎, t: Y}

    '&tok_def Z': {s: 🏠︎, t: Z}

    '&tok_def RET':   {s: 🏠︎, t: ╰┈➤}
    '&tok_def ESC':   {s: 🏠︎, t: ☢️}
    '&tok_def FSLH':  {s: 🏠︎, t: /}
    '&tok_def SEMI':  {s: 🏠︎, t: ;}
    '&tok_def SPACE': {s: 🏠︎, t: 🪐}

    # toggle default layer
    '&td_mm_a': {t: A_, s: ⌨️💃}
    '&td_mm_b': {t: B_, s: ⌨️💃}
    '&td_mm_c': {t: C_, s: ⌨️💃}
    '&td_mm_d': {t: D_, s: ⌨️💃}
    '&td_mm_e': {t: E_, s: ⌨️💃}

    '&td_mm_f': {t: F_, s: ⌨️💃}
    '&td_mm_g': {t: G_, s: ⌨️💃}
    '&td_mm_h': {t: H_, s: ⌨️💃}
    '&td_mm_i': {t: I_, s: ⌨️💃}
    '&td_mm_j': {t: J_, s: ⌨️💃}

    '&td_mm_k': {t: K_, s: ⌨️💃}
    '&td_mm_l': {t: L_, s: ⌨️💃}
    '&td_mm_m': {t: M_, s: ⌨️💃}
    '&td_mm_n': {t: N_, s: ⌨️💃}
    '&td_mm_o': {t: O_, s: ⌨️💃}

    '&td_mm_p': {t: P_, s: ⌨️💃}
    '&td_mm_q': {t: Q_, s: ⌨️💃}
    '&td_mm_r': {t: R_, s: ⌨️💃}
    '&td_mm_s': {t: S_, s: ⌨️💃}
    '&td_mm_t': {t: T_, s: ⌨️💃}

    '&td_mm_u': {t: U_, s: ⌨️💃}
    '&td_mm_v': {t: V_, s: ⌨️💃}
    '&td_mm_w': {t: W_, s: ⌨️💃}
    '&td_mm_x': {t: X_, s: ⌨️💃}
    '&td_mm_y': {t: Y_, s: ⌨️💃}

    '&td_mm_z': {t: Z_, s: ⌨️💃}

    '&add_spc COMMA': {t: ',_'}
    '&add_spsh DOT':  {t: '._'}


    # LED keys
    '&rgb_ug RGB_TOG':
      tap: 💡
    '&rgb_ug RGB_EFR':
      tap: 💡
      hold: ⏮
    '&rgb_ug RGB_EFF':
      tap: 💡
      hold: ⏭
    '&rgb_ug RGB_SPD':
      tap: 💡
      hold: 🐢
    '&rgb_ug RGB_SPI':
      tap: 💡
      hold: 🏎️
    '&rgb_ug RGB_HUI':
      tap: 🎨
      hold: ➕
    '&rgb_ug RGB_HUD':
      tap: 🎨
      hold: ➖
    '&rgb_ug RGB_SAI':
      tap: 🌈
      hold: ➕
    '&rgb_ug RGB_SAD':
      tap: 🌈
      hold: ➖
    '&rgb_ug RGB_BRI':
      tap: 🌗
      hold: ➕
    '&rgb_ug RGB_BRD':
      tap: 🌗
      hold: ➖


    # Bluetooth 𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗
    "&bt BT_CLR":
      tap: 📡
      shifted: 🗑️
    "&bt BT_SEL 0":
      tap: 📡
      shifted: 𝟎
    "&bt BT_SEL 1":
      tap: 📡
      shifted: 𝟏
    "&bt BT_SEL 2":
      tap: 📡
      shifted: 𝟐
    "&bt BT_SEL 3":
      tap: 📡
      shifted: 𝟑
    "&bt BT_SEL 4":
      tap: 📡
      shifted: 𝟒
    "&bt BT_SEL 5":
      tap: 📡
      shifted: 𝟓

  zmk_combos:

    # Layer Combos
    ##############
    combo_sticky_bt_led: {'k': 📌🚥}
    combo_to_smart_num: {'k': 🚩🔢}
    combo_smart_num: {'k': 🚩🔢}
    combo_to_default: {'k': 🚩🏠︎}
    combo_to_numbers: {'k': 🔘🔢}
    combo_to_navigation: {'k': 🔘🧭}

    # CrossRow Combos
    #################

    # opening braces and overlapping signs
    combo_curly_brace_l: {'k': '↗{',   a: mid, o: 0.01}
    combo_sqr_brace_l:   {'k': '↗[`↘', a: mid, o: 0.01}
    combo_brace_l:       {'k': '↗(',   a: mid, o: 0.01}
    ## closing braces
    combo_curly_brace_r: {'k': '↘}',    a: mid, o: 0.01}
    combo_sqr_brace_r:   {'k': '↘[%↗', a: mid, o: 0.01}
    combo_brace_r:       {'k': '↘)^↗', a: mid, o: 0.01}
    ## signs
    combo_caret:         {'k': '↘)^↗', a: mid, o: 0.01}
    combo_grave:         {'k': '↗[`↘', a: mid, o: 0.01}
    combo_perc:          {'k': '↘[%↗', a: mid, o: 0.01}

    # TopRow Combos
    ###############

    combo_star:          {'k': '*', a: top,    o: 0.1}
    combo_hash:          {'k': '#', a: top,    o: -0.1}

    # MidRow Combos
    ###############

    combo_ampers:        {'k': '&', a: top,    o: 0.235, dendron: true }
    combo_tilde:         {'k': '~', a: top,    o: 0.09}
    combo_at2:           {'k': '@', a: bottom, o: -0.08, p: [19,20,21,22]}
    combo_caps_word:     {'k': 🚩⏏}

    # BotRow Combos
    ###############

    combo_dollar:        {'k': '$', a: bottom, o: -0.1}
    combo_at:            {'k': '@', a: bottom, o: -0.0}

