draw_config:
  append_colon_to_layer_header: true
  dark_mode: true
  arc_radius: 6.0
  arc_scale: 1.0
  combo_h: 15.0
  combo_w: 30.0
  inner_pad_h: 2.0
  inner_pad_w: 2.0
  key_h: 61.0
  key_rx: 6.0
  key_ry: 6.0
  key_w: 65.0
  line_spacing: 1.2
  outer_pad_h: 56.0
  outer_pad_w: 30.0
  small_pad: 2.0
  split_gap: 30.0
  svg_style: |
    /* font and background color specifications */
    svg {
        font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 17px;
        text-rendering: optimizeLegibility;
        fill: #1c1c1c;
    }

    /* default key styling */
    rect {
        fill: #f6f8fa;
        stroke: #c9cccf;
        stroke-width: 1;
    }

    /* color accent for combo boxes */
    rect.combo {
        fill: #cdf;
    }

    /* color accent for held keys */
    rect.held, rect.combo.held {
        fill: #fdd;
    }

    /* color accent for ghost (optional) keys */
    rect.ghost, rect.combo.ghost {
        fill: #ddd;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
    }

    /* styling for layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        stroke: white;
        stroke-width: 2;
        paint-order: stroke;
    }

    /* styling for combo tap, and key shifted label text */
    text.combo, text.shifted {
        font-size: 10px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
    }
    /* styling for hold/shifted label text in combo box */
    text.hold, text.combo.hold {
        font-family: Roboto-Regular, Roboto, Arial, SansSerif;
        font-size: 10px;
        font-weight: bold;
        fill: cyan;
    }
    text.combo.shifted {
        font-size: 10px;
        stroke: none;
    }

    /* styling for combo dendrons */
    path {
        stroke-width: 1;
        stroke: gray;
        fill: none;
    }
