name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write  # allow workflow to commit to the repo

jobs:
  keymaps:
    uses: ./.github/workflows/create-keymaps.yaml
    with:
      commit_message: "[Autogen-Draw-Keymaps] ${{ github.event.head_commit.message }}"

  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

